// VGA specific...
#define DISP_IOCTL_SETMODE    1
#define DISP_IOCTL_SETCOLOR   2
#define DISP_IOCTL_DEFAULTPAL 3

// Generic
#define DISP_IOCTL_SETPIXEL   4
#define DISP_IOCTL_BLIT       5
#define DISP_IOCTL_DRAWLINE   6
#define DISP_IOCTL_DRAWRECT   7
#define DISP_IOCTL_DRAWCIRCLE 8
