// System call numbers
#define SYS_chdir   1
#define SYS_close   2
#define SYS_dup     3
#define SYS_exec    4
#define SYS_exit    5
#define SYS_fork    6
#define SYS_fstat   7
#define SYS_getpid  8
#define SYS_gettime 9
#define SYS_kill    10
#define SYS_link    11
#define SYS_mkdir   12
#define SYS_mknod   13
#define SYS_open    14
#define SYS_pipe    15
#define SYS_read    16
#define SYS_sbrk    17
#define SYS_sleep   18
#define SYS_unlink  19
#define SYS_uptime  20
#define SYS_wait    21
#define SYS_write   22
