// General ________________________________________________________________________

#define TXTMODE 0x03
#define GFXMODE 0x13


// Text mode (0x03) constants _____________________________________________________

#define TXTBUFFER      0xB8000  // physical address

#define NCOLS          80
#define NROWS          25
#define NCOLSxNROWS    2000  // NCOLS x NROWS

#define WIDTH_TXTMODE  720   // In mode 0x3, the screen resolution appears to be 720x400
#define HEIGHT_TXTMODE 400   //  https://en.wikipedia.org/wiki/Text_mode

#define COLWIDTH       9     // width in pixels of a column: WIDTH_TXTMODE / NCOLS
#define ROWHEIGHT      16    // height in pixels of a row:   HEIGHT_TXTMODE / NROWS

#define CTRL           0x3D4
#define DATA           0x3D5

#define TBLACK         0
#define TBLUE          1
#define TGREEN         2
#define TCYAN          3
#define TRED           4
#define TMAGENTA       5
#define TBROWN         6
#define TLIGHT_GREY    7
#define TDARK_GREY     8
#define TLIGHT_BLUE    9
#define TLIGHT_GREEN   10
#define TLIGHT_CYAN    11
#define TLIGHT_RED     12
#define TLIGHT_MAGNETA 13
#define TYELLOW        14
#define TWHITE         15

#define BACKSPACE      0x100


// Graphics mode (0x13) constants _________________________________________________

#define GFXBUFFER            0xA0000  // physical address

#define WIDTH_GFXMODE        320
#define HEIGHT_GFXMODE       200
#define WIDTHxHEIGHT_GFXMODE 64000  // WIDTH_GFXMODE x HEIGHT_GFXMODE

#define	VGA_AC_INDEX         0x3C0
#define	VGA_AC_WRITE         0x3C0
#define	VGA_MISC_WRITE       0x3C2
#define VGA_SEQ_INDEX        0x3C4
#define VGA_SEQ_DATA         0x3C5
#define	VGA_DAC_WRITE_INDEX	 0x3C8
#define	VGA_DAC_DATA		 0x3C9
#define VGA_GC_INDEX         0x3CE
#define VGA_GC_DATA          0x3CF
/*                 COLOR emulation   MONO emulation */
#define VGA_CRTC_INDEX       0x3D4         /* 0x3B4 */
#define VGA_CRTC_DATA        0x3D5         /* 0x3B5 */
#define	VGA_INSTAT_READ      0x3DA

#define	VGA_NUM_SEQ_REGS     5
#define	VGA_NUM_CRTC_REGS    25
#define	VGA_NUM_GC_REGS      9
#define	VGA_NUM_AC_REGS      21


// Mode registers _________________________________________________________________

// Register values for VGA Mode 0x03 (Text)
static char g_80x25_text [] = {

	// Miscellaneous
		0x67,
	// Sequencer
		0x03, 0x00, 0x03, 0x00, 0x02,
	// CRTC
		0x5F, 0x4F, 0x50, 0x82, 0x55, 0x81, 0xBF, 0x1F,
		0x00, 0x4F, 0x0D, 0x0E, 0x00, 0x00, 0x00, 0x50,
		0x9C, 0x0E, 0x8F, 0x28, 0x1F, 0x96, 0xB9, 0xA3,
		0xFF,
	// Graphics controller
		0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x0E, 0x00,
		0xFF,
	// Attribute controller
		0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x14, 0x07,
		0x38, 0x39, 0x3A, 0x3B, 0x3C, 0x3D, 0x3E, 0x3F,
		0x0C, 0x00, 0x0F, 0x08, 0x00
};

// Registers for VGA Mode 0x13 (Graphics)
static char g_320x200x256 [] = {

	// Miscellaneous
		0x63,
	// Sequencer
		0x03, 0x01, 0x0F, 0x00, 0x0E,
	// CRTC
		0x5F, 0x4F, 0x50, 0x82, 0x54, 0x80, 0xBF, 0x1F,
		0x00, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x9C, 0x0E, 0x8F, 0x28,	0x40, 0x96, 0xB9, 0xA3,
		0xFF,
	// Graphics controller
		0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x05, 0x0F,
		0xFF,
	// Attribute controller
		0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
		0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
		0x41, 0x00, 0x0F, 0x00,	0x00
};


// Palettes _______________________________________________________________________

/* An approximation of the standard 256-color VGA palette.
   The palette is generated by Noah Johnson's snippet:
    https://github.com/canidlogic/vgapal
*/
static char vga256_18bit_default [ 256 * 3 ] = {
	//
	 0,  0,  0,   0,  0, 42,   0, 42,  0,   0, 42, 42,
	42,  0,  0,  42,  0, 42,  42, 21,  0,  42, 42, 42,
	21, 21, 21,  21, 21, 63,  21, 63, 21,  21, 63, 63,
	63, 21, 21,  63, 21, 63,  63, 63, 21,  63, 63, 63,
	 0,  0,  0,   5,  5,  5,   8,  8,  8,  11, 11, 11,
	14, 14, 14,  17, 17, 17,  20, 20, 20,  24, 24, 24,
	28, 28, 28,  32, 32, 32,  36, 36, 36,  40, 40, 40,
	45, 45, 45,  50, 50, 50,  56, 56, 56,  63, 63, 63,
	 0,  0, 63,  16,  0, 63,  31,  0, 63,  47,  0, 63,
	63,  0, 63,  63,  0, 47,  63,  0, 31,  63,  0, 16,
	63,  0,  0,  63, 16,  0,  63, 31,  0,  63, 47,  0,
	63, 63,  0,  47, 63,  0,  31, 63,  0,  16, 63,  0,
	 0, 63,  0,   0, 63, 16,   0, 63, 31,   0, 63, 47,
	 0, 63, 63,   0, 47, 63,   0, 31, 63,   0, 16, 63,
	31, 31, 63,  39, 31, 63,  47, 31, 63,  55, 31, 63,
	63, 31, 63,  63, 31, 55,  63, 31, 47,  63, 31, 39,
	63, 31, 31,  63, 39, 31,  63, 47, 31,  63, 55, 31,
	63, 63, 31,  55, 63, 31,  47, 63, 31,  39, 63, 31,
	31, 63, 31,  31, 63, 39,  31, 63, 47,  31, 63, 55,
	31, 63, 63,  31, 55, 63,  31, 47, 63,  31, 39, 63,
	45, 45, 63,  49, 45, 63,  54, 45, 63,  58, 45, 63,
	63, 45, 63,  63, 45, 58,  63, 45, 54,  63, 45, 49,
	63, 45, 45,  63, 49, 45,  63, 54, 45,  63, 58, 45,
	63, 63, 45,  58, 63, 45,  54, 63, 45,  49, 63, 45,
	45, 63, 45,  45, 63, 49,  45, 63, 54,  45, 63, 58,
	45, 63, 63,  45, 58, 63,  45, 54, 63,  45, 49, 63,
	 0,  0, 28,   7,  0, 28,  14,  0, 28,  21,  0, 28,
	28,  0, 28,  28,  0, 21,  28,  0, 14,  28,  0,  7,
	28,  0,  0,  28,  7,  0,  28, 14,  0,  28, 21,  0,
	28, 28,  0,  21, 28,  0,  14, 28,  0,   7, 28,  0,
	 0, 28,  0,   0, 28,  7,   0, 28, 14,   0, 28, 21,
	 0, 28, 28,   0, 21, 28,   0, 14, 28,   0,  7, 28,
	14, 14, 28,  17, 14, 28,  21, 14, 28,  24, 14, 28,
	28, 14, 28,  28, 14, 24,  28, 14, 21,  28, 14, 17,
	28, 14, 14,  28, 17, 14,  28, 21, 14,  28, 24, 14,
	28, 28, 14,  24, 28, 14,  21, 28, 14,  17, 28, 14,
	14, 28, 14,  14, 28, 17,  14, 28, 21,  14, 28, 24,
	14, 28, 28,  14, 24, 28,  14, 21, 28,  14, 17, 28,
	20, 20, 28,  22, 20, 28,  24, 20, 28,  26, 20, 28,
	28, 20, 28,  28, 20, 26,  28, 20, 24,  28, 20, 22,
	28, 20, 20,  28, 22, 20,  28, 24, 20,  28, 26, 20,
	28, 28, 20,  26, 28, 20,  24, 28, 20,  22, 28, 20,
	20, 28, 20,  20, 28, 22,  20, 28, 24,  20, 28, 26,
	20, 28, 28,  20, 26, 28,  20, 24, 28,  20, 22, 28,
	 0,  0, 16,   4,  0, 16,   8,  0, 16,  12,  0, 16,
	16,  0, 16,  16,  0, 12,  16,  0,  8,  16,  0,  4,
	16,  0,  0,  16,  4,  0,  16,  8,  0,  16, 12,  0,
	16, 16,  0,  12, 16,  0,   8, 16,  0,   4, 16,  0,
	 0, 16,  0,   0, 16,  4,   0, 16,  8,   0, 16, 12,
	 0, 16, 16,   0, 12, 16,   0,  8, 16,   0,  4, 16,
	 8,  8, 16,  10,  8, 16,  12,  8, 16,  14,  8, 16,
	16,  8, 16,  16,  8, 14,  16,  8, 12,  16,  8, 10,
	16,  8,  8,  16, 10,  8,  16, 12,  8,  16, 14,  8,
	16, 16,  8,  14, 16,  8,  12, 16,  8,  10, 16,  8,
	 8, 16,  8,   8, 16, 10,   8, 16, 12,   8, 16, 14,
	 8, 16, 16,   8, 14, 16,   8, 12, 16,   8, 10, 16,
	11, 11, 16,  12, 11, 16,  13, 11, 16,  15, 11, 16,
	16, 11, 16,  16, 11, 15,  16, 11, 13,  16, 11, 12,
	16, 11, 11,  16, 12, 11,  16, 13, 11,  16, 15, 11,
	16, 16, 11,  15, 16, 11,  13, 16, 11,  12, 16, 11,
	11, 16, 11,  11, 16, 12,  11, 16, 13,  11, 16, 15,
	11, 16, 16,  11, 15, 16,  11, 13, 16,  11, 12, 16,
	 0,  0,  0,   0,  0,  0,   0,  0,  0,   0,  0,  0,
	 0,  0,  0,   0,  0,  0,   0,  0,  0,   0,  0,  0
};

// TODO:
/* A custom default palette that we will use instead
   of the (ugly) standard VGA 256 palette.
*/
// static char vga256_18bit_custom [ 256 * 3 ] = {};


/* It seems that a palette is shared between VGA modes,
   but that indices are not consistent across the modes...
   The following table is used to put the colors where
   text mode (0x03) expects to find them. It is retrieved
   from this forum post where more information can be found:
   https://forum.osdev.org/viewtopic.php?f=1&t=23753&p=192800#p192800
*/
static char EGAtoVGA [ 16 ] = {
	//
	       // EGA   VGA
	0x00,  // 0x0   0x00  Black
	0x01,  // 0x1   0x01  Blue
	0x02,  // 0x2   0x02  Green
	0x03,  // 0x3   0x03  Cyan
	0x04,  // 0x4   0x04  Red
	0x05,  // 0x5   0x05  Magenta
	0x14,  // 0x6   0x14  Brown
	0x07,  // 0x7   0x07  Light Grey
	0x38,  // 0x8   0x38  Grey
	0x39,  // 0x9   0x39  Light Blue
	0x3A,  // 0xA   0x3A  Light Green
	0x3B,  // 0xB   0x3B  Light Cyan
	0x3C,  // 0xC   0x3C  Light Red
	0x3D,  // 0xD   0x3D  Light Magenta
	0x3E,  // 0xE   0x3E  Yellow
	0x3F,  // 0xF   0x3F  White
};


// Fonts __________________________________________________________________________

// see 'kfonts.h'
